# Generated by Django 4.1.6 on 2023-02-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_name', models.CharField(max_length=250)),
                ('img3', models.ImageField(upload_to='pics2')),
                ('desc3', models.TextField()),
            ],
        ),
    ]
